#@ load("@ytt:data", "data")
apiVersion: v1
kind: Service
metadata:
  name: capi
  namespace: #@ data.values.system_namespace
spec:
  type: ClusterIP
  ports:
    - port: 9024
      targetPort: 9024
      protocol: TCP
      name: http
    - port: 9023
      targetPort: 9023
      protocol: TCP
      name: http-internal
  selector:
    app.kubernetes.io/name: cf-api-server
